### PR TITLE
Update createServer.js

### PR DESCRIPTION
**Pull request by Sliden101**
remove fivem

### CODE REVIEW

**Comment by omsenjalia** [comment]
Why

**Comment by PadowYT2** [comment]
Because pterodactyl can't to make it and licensing is bad for ptero afaik

**Comment by djohts** [comment]
> Because pterodactyl can't to make it and licensing is bad for ptero afaik

aren't they fine again

**Comment by PadowYT2** [comment]
oh yes as i see, this should be closed @Sliden101 sussy

**Pull request closed without merging**
