### PR TITLE
Add error handling

### PR DESCRIPTION
**Pull request by Deveroonie**

### CODE REVIEW

**Comment by Jonfirexbox** [comment]
They added this then removed it since so many errors would go through

**Comment by Kyro3400** [comment]
whats the point of adding this?

**Review by ThePedroo — CHANGES_REQUESTED** [review]
I can be wrong, but you're forgetting a ' & ".

**Comment by PadowYT2** [comment]
What is this formatting :skull:

**Review by PadowYT2 — CHANGES_REQUESTED** [review]
```js
// Error handler
client.on('error', err => {
  console.log("An error occured.")
});

// Bot login
client.login(config.DiscordBot.Token); 
```

**Pull request closed without merging**
